# Generated by Django 3.2.8 on 2022-01-22 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
        ('integrantes', '0004_alter_integrantes_service_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrantes',
            name='service_area',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='servicos.servicos'),
        ),
    ]
